location             = "eastus2"
resource_group_name  = "rg-rickylab-dev-02"
app_serviceplan_name = "asp-simple-dev-02"
linux_web_app_name   = "app-simple-app-dev-02"
key_vault_name       = "kv-rickylab-dev-02"
secret_name          = "secret-rickylab-dev-02"
asp_sku_name         = "B1"
