location             = "centralus"
resource_group_name  = "rg-rickylab-prod-02"
app_serviceplan_name = "asp-simple-prod-02"
linux_web_app_name   = "app-simple-app-prod-02"
key_vault_name       = "kv-rickylab-prod-02"
secret_name          = "secret-rickylab-prod-02"
asp_sku_name         = "S1"
