name: Terraform Deploy - devops-primer-mod3-rickybarbour

env:
  ARM_TENANT_ID: '653fcdc1-a3dc-4588-96c4-ef684fc1232b'
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: |
          terraform init --backend-config="container_name=tfstate-devops-primer-mod3-rickybarbour-np" # To use the production state file, use container_name=tfstate-devops-primer-mod3-rickybarbour-p
          
    - name: Terraform Validate
      id: validate
      run: terraform validate              

    - name: Terraform Plan
      id: terraform-plan
      run: terraform plan -var-file="nonprod.tfvars" --out=build.tfplan
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: 'nonprod_tfplan'
        path: 'build.tfplan'
        retention-days: 5      
        
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:       
      - name: Download Terraform Artifact
        uses: actions/download-artifact@v3
        with:
          name: 'nonprod_tfplan'
          path: 'nonprod_tfplan.zip' 
          
      - name: Decompress Terraform Artifact
        run: unzip 'nonprod_tfplan'          
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2  
        
      - name: Terraform Init
        run: |
            terraform init --backend-config="container_name=tfstate-devops-primer-mod3-rickybarbour-np" # To use the production state file, use container_name=tfstate-devops-primer-mod3-rickybarbour-p        

      - name: Terraform Apply
        id: terraform-apply
        run: terraform apply build.tfplan -var-file="nonprod.tfvars" -auto-approve -input=false

