name: Terraform Deploy - devops-primer-mod3-rickybarbour

env:
  ARM_TENANT_ID: '653fcdc1-a3dc-4588-96c4-ef684fc1232b'
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

on:
  workflow_dispatch:

jobs:
  setup-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: |
          terraform init --backend-config="container_name=tfstate-devops-primer-mod3-rickybarbour-np" # To use the production state file, use container_name=tfstate-devops-primer-mod3-rickybarbour-p
          
    - name: Terraform Validate
      id: validate
      run: terraform validate          

#    - name: Azure Login
#      id: azure-login
#      uses: azure/login@v1
#      with:
#          creds: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ env.ARM_TENANT_ID }}"}'          

    - name: Terraform Plan
      id: terraform-plan
      run: terraform plan -var-file="nonprod.tfvars"

    - name: Terraform Apply
      id: terraform-apply
      run: terraform apply -var-file="nonprod.tfvars" -auto-approve -input=false

