name: Terraform Deploy - devops-primer-mod3-rickybarbour

env:
  ARM_TENANT_ID: '653fcdc1-a3dc-4588-96c4-ef684fc1232b'
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: |
          terraform init --backend-config="container_name=tfstate-devops-primer-mod3-rickybarbour-np" # To use the production state file, use container_name=tfstate-devops-primer-mod3-rickybarbour-p
          
    - name: Terraform Validate
      id: validate
      run: terraform validate              

    - name: Terraform Plan
      id: terraform-plan
      run: terraform plan -var-file="nonprod.tfvars" --out=build.tfplan
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: 'nonprod_tfplan'
        path: '${{ github.workspace }}/build.tfplan'
        retention-days: 5   
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: 'lockfile'
        path: '${{ github.workspace }}/.terraform.lock.hcl'
        retention-days: 5             
        
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:       
      - name: Download Terraform Artifact
        uses: actions/download-artifact@v3
        with:
          name: 'nonprod_tfplan'
          path: '${{ github.workspace }}' 
          
      - name: Download Terraform Lockfile
        uses: actions/download-artifact@v3
        with:
          name: 'lockfile'
          path: '${{ github.workspace }}/.terraform.lock.hcl'          
      
      - name: Display structure of downloaded files
        run: ls -R
        
      - name: Cat the file
        run: cat build.tfplan        
          
      - name: Unzip Terraform Artifact
        uses: montudor/action-zip@v1
        with: 
          args: unzip build.tfplan 
          
      - name: Unzip Terraform Lockfile
        uses: montudor/action-zip@v1
        with: 
          args: unzip .terraform.lock.hcl           
          
      - name: Display structure of unzipped files
        run: ls -R          
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2  
        
      - name: Terraform Init
        run: |
            terraform init --backend-config="container_name=tfstate-devops-primer-mod3-rickybarbour-np" # To use the production state file, use container_name=tfstate-devops-primer-mod3-rickybarbour-p  
            rm .terraform.lock.hcl

      - name: Terraform Apply
        id: terraform-apply
        run: terraform apply build.tfplan

